### ISSUE TITLE
Thaumcraft world gen crashes (RTG 0.0.13)

### ISSUE THREAD

**Issue by wkalinin** [Team-RTG/Realistic-Terrain-Generation#249]
Here's the log: http://pastebin.com/SFeberW8
Here's the mod list: http://pastebin.com/CXGZFvcA

**Comment by whichonespink44** [comment]
Fixed in 7252ee9

**Comment by wkalinin** [comment]
Thanks, that was fast.

**Comment by srs-bsns** [comment]
@whichonespink44, This is not fixed. I'm still getting crashes: http://pastebin.com/Wnccqwpx

**Comment by whichonespink44** [comment]
This should be fixed in the latest dev version. Here's a snapshot if anyone wants to test it out before I close this issue again: https://goo.gl/EAvQje

**Comment by whichonespink44** [comment]
@srs-bsns - thanks for the detailed report... hopefully the latest changes should fix this one for good.

**Comment by whichonespink44** [comment]
Fixed in 0.0.16
