### ISSUE TITLE
Crash with ChromatiCraft

### ISSUE THREAD

**Issue by Haggle1996** [Team-RTG/Realistic-Terrain-Generation#382]
With minimal modset, on creating a brand new world with BoP 1521 and ChromatiCraft.

https://gist.github.com/Haggle1996/ecf181d09d780a633402

With my full modpack, receive a slightly different error, indicating biome 100 (CC Skyland Biome): https://gist.github.com/Haggle1996/ebf26654848e9fae3fbf

Full fml-client-latest from minimal execution.
https://gist.github.com/Haggle1996/feeb4bb0ed292ed217a9

RTG Biome Layout == false.

EDIT:
And for kicks and giggles:
RTG.cfg - https://gist.github.com/Haggle1996/b417cbb085f36f573135
ClimateControl.cfg - https://gist.github.com/Haggle1996/b3ee4177dd980e147246

B:ReikasBiomesOn=true and B:BoPBiomesOn=true in appropriate files

EDIT2:
Nothing new here, but here's the same crash log with the absolute minimal modset: forge, dragonapi, chromaticraft, climatecontrol, biomes o plenty, rtg.
https://gist.github.com/Haggle1996/8c24672f8dbb2868473b

**Comment by Zeno410** [comment]
I have a candidate fix in for this. RTG was crashing trying to create an RTG chunk manager for an alternate dimension (which we currently think it shouldn't do). I just added a line to make it generate a vanilla chunk manager for all non-overworld dimensions.

**Comment by Haggle1996** [comment]
I understand why you did it, but this is probably a more sane approach and leaves me with my limbs intact. :)

**Comment by Zeno410** [comment]
The crash was to know we were doing something wrong. Otherwise it would still be serving RTGChunkManagers to alternate dimensions.

**Comment by whichonespink44** [comment]
Fixed in aea3b24

**Comment by Haggle1996** [comment]
Still crashing with ChromatiCraft.

https://gist.github.com/Haggle1996/9f17cbb55eef7d0db791

**Comment by Haggle1996** [comment]
ChromatiCraft has 3 biomes that shouldn't spawn in the overworld (Skyland, Plains, and Island). I have a hunch these are getting picked up by RTG and/or Climate Control.

**Comment by MrGraphic** [comment]
The same can happen with vanilla biomes. I had one with biome id 161.

**Comment by whichonespink44** [comment]
Just a quick update on this one... all of these crashes are happening because RTG doesn't have realistic versions of those biomes, and CC needs them, even though it won't always spawn them. So... in order to fix this, we need to add the missing biomes to RTG, which we're currently working on and should be in the next snapshot, which will probably be released tomorrow.

**Comment by Zeno410** [comment]
For now just set the incidences of those biomes to 0 in the ReikasBiomesinCC config.

**Comment by whichonespink44** [comment]
Should be fixed in snapshot 4. Let us know if not and we'll re-open.

**Comment by Haggle1996** [comment]
Still happening when I enable the remaining 3 ChromatiCraft biomes (Skyland, Plain, and Island). I'm wondering if these biomes are how @ReikaKalseki injects the ChromatiCraft temples into the overworld? The overworld ChromatiCraft structures are not generating in 0.5.0 snapshot 4.

**Comment by whichonespink44** [comment]
Hmm, looks like this one's gonna need some further investigation. I've re-opened issue and will look into it.

**Comment by Haggle1996** [comment]
https://github.com/ReikaKalseki/ChromatiCraft/blob/d43813796a1a430ba1fade6501d065142bbece9c/World/DungeonGenerator.java is the relevant code.

BTW, despite lot's of issues with 0.5.0, you're all doing a great job. Keep it up!

**Comment by Haggle1996** [comment]
The bug should stay open due to the crash with those biome IDs -- however, I can confirm ChromatiCraft structures are generating in snapshot 4. I pregenerated a 2000 block radius of OCEAN, then removed all non-relevant blocks...found 2. Looking at how they generate, I imagine the Railcraft Abyssal Stone is interfering with their spawn rate. I have a hunch that once the abyssal stone generates underground again, instead of it's current floating in mid-ocean (reported elsewhere), we'll see more ChromatiCraft structures.

**Comment by ReikaKalseki** [comment]
No, those three biomes are unused, originally planned for the dimension.

**Comment by whichonespink44** [comment]
@Zeno410 If I create realistic versions of those 3 ChromatiCraft biomes (Skyland, Plain, and Island) will Climate Control know to not place them?

**Comment by ReikaKalseki** [comment]
Do not bother. I control the entire CC dimension worldgen process, making any effort on your part wasted.

**Comment by whichonespink44** [comment]
@ReikaKalseki RTG only generates Overworld biomes in the Overworld, so we don't want to add support for them in order to _generate_ them... we want to add support so that we can prevent them from trying to generate in the Overworld.

@Zeno410 - does CC need to add explicit support for those 3 biomes in order to prevent them from generating? Or is it something that RTG has to do?

**Comment by Zeno410** [comment]
CC should not generate the biomes by default. I thought I'd already done that, but I'll check. Users can "force in" the biomes but that's their problem if they choose to do so.
