### ISSUE TITLE
[1.7.10][RTG-1.0.1] Crashes on creating non-RTG worlds

### ISSUE THREAD

**Issue by OneEyeMaker** [Team-RTG/Realistic-Terrain-Generation#816]
Hello.
I found simple and strange bug. If I understand correctly, RTG tries to properly select material for villages in desert biomes.
But there is bug, that crashes the world, if world type **is not** _Realistic_. (I just tried to create simple superflat world).
Also, as I see in code, RTG doesn't handle villages in desert biomes if UBC is installed. (UBC has config option to replace all stone stuff in villages). And I often see  (_UBfied_) cobblestone villages in desert.
Please, fix these problems (check type of world and check UBC stones in villages). Both these ones are in [this method](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.7.10-master/src/main/java/rtg/event/EventManagerRTG.java#L189).

[Crash report](http://pastebin.com/b1vU8hFM).

P. S. Sorry for my English, I'm from Russia.

**Comment by steelshot** [comment]
Yeah, im getting the same crash report, tried to make myself a superflat world for bug testing -> boom crash straight away.

http://pastebin.com/JL0c5yVC

**Comment by whichonespink44** [comment]
I'm unable to reproduce this crash.

Using only RTG 1.0.1 and a few utility mods, I can load up a Superflat world just fine.

In fact, RTG has code that unregisters its event handlers if not in an RTG world:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.7.10-master/src/main/java/rtg/event/EventManagerRTG.java#L87-L96

That's basically saying "hey, if I'm not in an RTG world, then I'm not gonna interfere with anything" - so the only thing I can think of is that another mod is interfering somehow. If I had to guess, I'd say that Tinkers Construct and/or AgriCraft is using ASM to hijack our event handlers and somehow re-registering them?

@Team-RTG/rtg-writers Any other ideas?

**Comment by Zeno410** [comment]
Not Tinker's by itself, because I use it without trouble.

**Comment by whichonespink44** [comment]
We need to test that code linked above to make sure it's getting fired when the world loads.

**Comment by srs-bsns** [comment]
As I mentioned earlier in chat, I was able to reproduce this crash with RTG and UBC in a superflat world (desert preset).
I'm not sure the event manager is getting properly unregistered with the current design.
I'm been messing about with a fix that seems to work just fine, but I've been getting side-tracked, so I haven't been able to do thorough testing.
I should have a fix ready tomorrow sometime.

**Comment by srs-bsns** [comment]
Fixed in: #820

**Comment by OneEyeMaker** [comment]
I tested version 1.1.0-snapshot-1.
Village generation in non-RTG worlds doesn't cause crash. Thank you for it.
But, one problem isn't fixed: RTG replaces **_only_** vanilla stone/cobblestone stuff in villages.
On my modpack I've also UBC installed. And, if I understand correctly, UBC runs _before_ RTG.
Result of that:
http://imgur.com/5RVWmjO
I guess, you should just add another checks (is UBC loaded and is block from UBC).

**Comment by whichonespink44** [comment]
RTG no longer replaces village blocks, so that's probably an issue with UBC and should be reported on its forum thread.

To confirm, try removing UBC and loading a **new world** with the **same seed** and flying to the coords in the screenshot you posted. If it looks like a normal desert village, then it's not a bug with RTG.

I'm closing this as the original bug has been fixed, but please report back here with any updates on the village bug. If it turns out to be a problem with RTG, we'll create a separate issue for it.
